### ISSUE TITLE
Where can I find the lyric annotation?

### ISSUE THREAD

**Issue by ivylijingru** [xiaoxue1117/ALTP_chords_lyrics#1]
Thank you for sharing the dataset. I am doing research in this field now, and I am curious about how to find lyric annotations for the segmented audio. Thanks

**Comment by xiaoxue1117** [comment]
> Thank you for sharing the dataset. I am doing research in this field now, and I am curious about how to find lyric annotations for the segmented audio. Thanks

Thank you for your interest! The lyrics annotations are from the original papers of Hansen, Jamendo and mauch datasets.

**Comment by ivylijingru** [comment]
Thank you for your response. So shall we contact the authors directly to obtain the datasets? As far as I am concerned, the datasets are not published except for Jamendo (on GitHub).

**Comment by xiaoxue1117** [comment]
> Thank you for your response. So shall we contact the authors directly to obtain the datasets? As far as I am concerned, the datasets are not published except for Jamendo (on GitHub).

You may contact the authors directly.
